version: '3.8'
services:
  mongo:
    image: mongo:4.2.2
    container_name: financial_dashboard_mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    image: financial_dashboard_backend_image
    container_name: financial_dashboard_backend_container
    environment:
      - MONGODB_URI=yourmongodburi
    ports:
      - 3000:3000
    depends_on:
      - mongo

  frontend:
    image: financial_dashboard_frontend_image
    container_name: financial_dashboard_frontend_container
    ports:
      - 8080:80
    depends_on:
      - backend

volumes:
  mongo-data:
